- include: repositories.yml

- name: Enable fastestmirror for DNF
  lineinfile:
    dest: /etc/dnf/dnf.conf
    line: 'fastestmirror=1'
    backup: yes

- name: Install packages (User)
  dnf:
    name: "{{item}}"
    state: present
  with_items:
    - awscli
    - tinc
    - vim
    - mc
    - docker
    - pandoc
    - tomb
    - tmux
    - hplip
    - hplip-gui
    - libvirt
    - virt-manager
    - samba
    - rofi
    - pass
    - keychain
    - zsh
    - google-chrome-beta
    - beesu
    - zathura
    - zathura-plugins-all
    - neomutt
    - neovim
    - isync
    - notmuch
    - winswitch
    - powertop
    - smartmontools
    - the_silver_searcher
    - freetype-freeworld
    - gnome-tweak-tool
    - fasd
    - htop
    - elinks
    - google-noto-sans-fonts
    - google-noto-serif-fonts
    - adobe-source-code-pro-fonts
    - adobe-source-sans-pro-fonts
    - gnome-shell-extension-gpaste
    - gnome-shell-extension-drive-menu
    - gnome-shell-extension-places-menu
    - gnome-shell-extension-openweather
    - gnome-shell-extension-windowsNavigator
    - gnome-shell-extension-native-window-placement
    - xsel
    - xdotool

- name: Install the 'Development tools' package group
  dnf:
    name: "@Development tools"
    state: present

- name: Install packages (Development)
  dnf:
    name: "{{item}}"
    state: present
  with_items:
    - gcc
    - gcc-c++
    - openssl-devel
    - cmake
    - golang
    - golang-bin
    - python-devel
    - python3-devel
    - ctags
    - ruby
    - ruby-devel
    - nodejs
    # neovim
    - python2-greenlet-devel
    - python-neovim
    - python3-neovim
    - python-neovim-gui
    - python3-neovim-gui
    - ncurses-compat-libs
    # /neovim
    - python-firewall
    - python3-firewall
    - python-pip
    - python3-pip
    - perl
    - perl-open
    - expect
    - ansible-lint

- name: Install npm modules
  npm:
    name: "{{item}}"
    global: True
    state: present
  with_items:
    - diff-so-fancy

- name: Install ruby gems
  gem:
    name: "{{item}}"
    state: present
    user_install: True
  with_items:
    - overcommit
  become: yes
  become_user: "{{local_user}}"

- name: Install python modules
  pip:
    name: "{{item}}"
    state: present
    extra_args: '--user'
  with_items:
    - bumpversion
  become: yes
  become_user: "{{local_user}}"
