- include: repositories.yml

- name: Enable fastestmirror for DNF
  lineinfile:
    dest: /etc/dnf/dnf.conf
    line: 'fastestmirror=1'
    backup: yes

- name: Install packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ user_packages_cli }}"
    - "{{ user_packages_gui }}"
    - "{{ system_packages }}"
    - "{{ development_packages }}"

- name: Install the 'Development tools' package group
  dnf:
    name: "@Development tools"
    state: present


- name: Install npm modules
  npm:
    name: "{{ item }}"
    global: True
    state: present
  with_items:
    - "{{ npm_modules }}"

- name: Install ruby gems
  gem:
    name: "{{ item  }}"
    state: present
    user_install: True
  with_items:
    - "{{ ruby_gems }}"
  become: yes
  become_user: "{{ local_user }}"

- name: Install python modules
  pip:
    name: "{{ item }}"
    state: present
    extra_args: '--user'
    executable: 'pip3'
  with_items:
    - "{{ pip_modules }}"
  become: yes
  become_user: "{{ local_user }}"

- name: Check for go binaries
  stat:
    # this is not optimal, but unfortunately ansible (still) does not switch
    # env context for the become_user
    path: "{{ go.path }}/{{ item.name }}"
  with_items: "{{go.binaries}}"
  register: gobinaries_installed
  become: yes
  become_user: "{{ local_user }}"

- name: Install missing go binaries
  command: go get {{ item[0].url }}
  args:
    creates: "/home/{{ local_user }}/go/bin/{{ item[0].name }}"
  environment:
    GOPATH: "{{ go.path }}"
  with_nested:
    - "{{ go.binaries }}"
    - "{{ gobinaries_installed.results }}"
  when: not item[1].stat.exists
  become: yes
  become_user: "{{ local_user }}"
