---
- include: selinux.yml
- include: gnomekeyring.yml
- include: discards_resume.yml

- name: Template smb.conf for Samba
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    backup: yes
  notify:
    - Reload samba

- name: Template main.cf for postfix (additional commands in there)
  template:
    src: postfix.main.cf.j2
    dest: /etc/postfix/main.cf
    backup: yes
  notify:
    - Reload postfix

- name: Template btrfs-scrub@ timers and service files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    - { src: btrfs-scrub@.service.j2, dest: /etc/systemd/system/btrfs-scrub@.service }
    - { src: btrfs-scrub@.timer.j2, dest: /etc/systemd/system/btrfs-scrub@.timer }
  notify:
    Reload systemd

- include: services.yml


- name: Configure firewalld
  firewalld:
    service: "{{item}}"
    permanent: True
    state: enabled
  with_items:
    - samba
    - samba-client
    - tinc
    - dropbox-lansync
    - mosh
    - ssh
    - mdns
  notify: Reload firewalld
