---
- name: Reload samba
  service:
    name: smb
    state: restarted
- name: Reload postfix
  service:
    name: postfix
    state: restarted
- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded
- name: Reload systemd
  command: systemctl daemon-reload
